### ISSUE TITLE
[問] 是否可以提供繁體中文的翻譯/如何翻譯

### ISSUE THREAD

**Issue by everland-3769** [StarCitizenToolBox/RSILauncherEnhance#1]
同標題。

**Comment by xkeyC** [comment]
目前 [main.js](https://github.com/StarCitizenToolBox/RSILauncherEnhance/blob/main/main.js)  是一个 2M 左右的 js 文件，你这边要做翻译的话，参考  9396 行的代码，创建一个 const 的 JS map ，并翻译文本，剩下的交给我来做即可。

同样的，如果我超过 24 小时未回复，说明我没有及时看到此消息，请在 IM 即时通讯软件 （QQ、Steam ）或 发送邮件 来提醒我。

![image](https://github.com/StarCitizenToolBox/RSILauncherEnhance/assets/39891083/77ffa7b2-1816-4610-a95f-7f965952f6e5)

**Comment by everland-3769** [comment]
我了解了。跟你確認一下，所有需要翻譯的文本是9398~9708行之間的文本嗎？

**Comment by xkeyC** [comment]
> 我了解了。跟你確認一下，所有需要翻譯的文本是9398~9708行之間的文本嗎？

对，就是这一整个 map
