### ISSUE TITLE
啟動器版本已更新到 V2.0.2 版本

### ISSUE THREAD

**Issue by everland-3769** [StarCitizenToolBox/RSILauncherEnhance#4]
需要將啟動器增強功能一同更新

**Comment by xkeyC** [comment]
@everland-3769 简体中文已更新，请对应更新繁体文本，今天晚些时候将会发版

**Comment by everland-3769** [comment]
@xkeyC 這是更新繁體中文後的版本

[OneDrive](https://1drv.ms/u/s!AsMyDwsDmXY4iZIZ8cHEthUij_EdeQ?e=JVGwYJ)
