### ISSUE TITLE
2.0.3 main.js 繁體中文翻譯更新

### ISSUE THREAD

**Issue by everland-3769** [StarCitizenToolBox/RSILauncherEnhance#5]
2.0.3 main.js 的繁體中文翻譯已更新

[OneDrive](https://1drv.ms/f/s!AsMyDwsDmXY4iZYAjwHZ4GV6oMn1og?e=IRYkUH)

**Comment by xkeyC** [comment]
已更新繁体中文部分。
注：已安装过 2.0.3 补丁的用户可能需要手动删除 'launcher_enhance_data' 里的文件才可获得最新补丁。
